# Generated by Django 5.0.2 on 2024-02-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_package_id', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('mail_sent', models.BooleanField()),
            ],
        ),
    ]
