# Generated by Django 5.0.2 on 2024-02-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='mail_sent_date',
            field=models.DateTimeField(null=True),
        ),
    ]
