# Generated by Django 5.0.2 on 2024-02-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emailnotification_mail_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='assignee_mail',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='author_mail',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='responsible_mail',
            field=models.CharField(null=True),
        ),
    ]
