# Generated by Django 5.0.2 on 2024-02-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_emailnotification_assignee_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
