# Generated by Django 5.0.2 on 2024-02-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_emailnotification_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='is_closed',
            new_name='is_marked_as_closed',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
