# Generated by Django 5.0.2 on 2024-02-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_is_closed_emailnotification_is_marked_as_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='assignee_mail',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='author_mail',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='mail_sent_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='responsible_mail',
            field=models.CharField(default=None, null=True),
        ),
    ]
